pub enum Opcode {
    NIMP(u8),

    NOP,
    LXIB,
    STAXB,
    INXB,
    INRB,
    DCRB,
    MVIB,
    RLC,

    DADB,
    LDAXB,
    DCXB,
    INRC,
    DCRC,
    MVIC,
    RRC,

    LXID,
    STAXD,
    INXD,
    INRD,
    DCRD,
    MVID,
    RAL,

    DADD,
    LDAXD,
    DCXD,
    INRE,
    DCRE,
    MVIE,
    RAR,

    LXIH,
    SHLD,
    INXH,
    INRH,
    DCRH,
    MVIH,

    DADH,
    LHLD,
    DCXH,
    INRL,
    DCRL,
    MVIL,
    CMA,
}

impl Opcode {
    pub fn convert(n: u8) -> Opcode {
        match n {
            0x00 => Opcode::NOP,
            0x01 => Opcode::LXIB,
            0x02 => Opcode::STAXB,
            0x03 => Opcode::INXB,
            0x04 => Opcode::INRB,
            0x05 => Opcode::DCRB,
            0x06 => Opcode::MVIB,
            0x07 => Opcode::RLC,
            
            0x08 => Opcode::NOP,
            0x09 => Opcode::DADB,
            0x0a => Opcode::LDAXB,
            0x0b => Opcode::DCXB,
            0x0c => Opcode::INRC,
            0x0d => Opcode::DCRC,
            0x0e => Opcode::MVIC,
            0x0f => Opcode::RRC,
            
            0x10 => Opcode::NOP,
            0x11 => Opcode::LXID,
            0x12 => Opcode::STAXD,
            0x13 => Opcode::INXD,
            0x14 => Opcode::INRD,
            0x15 => Opcode::DCRD,
            0x16 => Opcode::MVID,
            0x17 => Opcode::RAL,

            0x18 => Opcode::NOP,
            0x19 => Opcode::DADD,
            0x1a => Opcode::LDAXD,
            0x1b => Opcode::DCXD,
            0x1c => Opcode::INRE,
            0x1d => Opcode::DCRE,
            0x1e => Opcode::MVIE,
            0x1f => Opcode::RAR,
            //
            0x20 => Opcode::NOP,        // RIM - special
            0x21 => Opcode::LXIH,
            0x22 => Opcode::SHLD,
            0x23 => Opcode::INXH,
            0x24 => Opcode::INRH,
            0x25 => Opcode::DCRH,
            0x26 => Opcode::MVIH,
            0x27 => Opcode::NOP,        // DAA - special

            0x28 => Opcode::NOP,
            0x29 => Opcode::DADH,
            0x2a => Opcode::LHLD,
            0x2b => Opcode::DCXH,
            0x2c => Opcode::INRL,
            0x2d => Opcode::DCRL,
            0x2e => Opcode::MVIL,
            0x2f => Opcode::CMA,
            //
            0x30 => Opcode::NIMP(n),
            0x31 => Opcode::NIMP(n),
            0x32 => Opcode::NIMP(n),
            0x33 => Opcode::NIMP(n),
            0x34 => Opcode::NIMP(n),
            0x35 => Opcode::NIMP(n),
            0x36 => Opcode::NIMP(n),
            0x37 => Opcode::NIMP(n),
            0x38 => Opcode::NIMP(n),
            0x39 => Opcode::NIMP(n),
            0x3a => Opcode::NIMP(n),
            0x3b => Opcode::NIMP(n),
            0x3c => Opcode::NIMP(n),
            0x3d => Opcode::NIMP(n),
            0x3e => Opcode::NIMP(n),
            0x3f => Opcode::NIMP(n),
            //
            0x40 => Opcode::NIMP(n),
            0x41 => Opcode::NIMP(n),
            0x42 => Opcode::NIMP(n),
            0x43 => Opcode::NIMP(n),
            0x44 => Opcode::NIMP(n),
            0x45 => Opcode::NIMP(n),
            0x46 => Opcode::NIMP(n),
            0x47 => Opcode::NIMP(n),
            0x48 => Opcode::NIMP(n),
            0x49 => Opcode::NIMP(n),
            0x4a => Opcode::NIMP(n),
            0x4b => Opcode::NIMP(n),
            0x4c => Opcode::NIMP(n),
            0x4d => Opcode::NIMP(n),
            0x4e => Opcode::NIMP(n),
            0x4f => Opcode::NIMP(n),
            //
            0x50 => Opcode::NIMP(n),
            0x51 => Opcode::NIMP(n),
            0x52 => Opcode::NIMP(n),
            0x53 => Opcode::NIMP(n),
            0x54 => Opcode::NIMP(n),
            0x55 => Opcode::NIMP(n),
            0x56 => Opcode::NIMP(n),
            0x57 => Opcode::NIMP(n),
            0x58 => Opcode::NIMP(n),
            0x59 => Opcode::NIMP(n),
            0x5a => Opcode::NIMP(n),
            0x5b => Opcode::NIMP(n),
            0x5c => Opcode::NIMP(n),
            0x5d => Opcode::NIMP(n),
            0x5e => Opcode::NIMP(n),
            0x5f => Opcode::NIMP(n),
            //
            0x60 => Opcode::NIMP(n),
            0x61 => Opcode::NIMP(n),
            0x62 => Opcode::NIMP(n),
            0x63 => Opcode::NIMP(n),
            0x64 => Opcode::NIMP(n),
            0x65 => Opcode::NIMP(n),
            0x66 => Opcode::NIMP(n),
            0x67 => Opcode::NIMP(n),
            0x68 => Opcode::NIMP(n),
            0x69 => Opcode::NIMP(n),
            0x6a => Opcode::NIMP(n),
            0x6b => Opcode::NIMP(n),
            0x6c => Opcode::NIMP(n),
            0x6d => Opcode::NIMP(n),
            0x6e => Opcode::NIMP(n),
            0x6f => Opcode::NIMP(n),
            //
            0x70 => Opcode::NIMP(n),
            0x71 => Opcode::NIMP(n),
            0x72 => Opcode::NIMP(n),
            0x73 => Opcode::NIMP(n),
            0x74 => Opcode::NIMP(n),
            0x75 => Opcode::NIMP(n),
            0x76 => Opcode::NIMP(n),
            0x77 => Opcode::NIMP(n),
            0x78 => Opcode::NIMP(n),
            0x79 => Opcode::NIMP(n),
            0x7a => Opcode::NIMP(n),
            0x7b => Opcode::NIMP(n),
            0x7c => Opcode::NIMP(n),
            0x7d => Opcode::NIMP(n),
            0x7e => Opcode::NIMP(n),
            0x7f => Opcode::NIMP(n),
            //
            0x80 => Opcode::NIMP(n),
            0x81 => Opcode::NIMP(n),
            0x82 => Opcode::NIMP(n),
            0x83 => Opcode::NIMP(n),
            0x84 => Opcode::NIMP(n),
            0x85 => Opcode::NIMP(n),
            0x86 => Opcode::NIMP(n),
            0x87 => Opcode::NIMP(n),
            0x88 => Opcode::NIMP(n),
            0x89 => Opcode::NIMP(n),
            0x8a => Opcode::NIMP(n),
            0x8b => Opcode::NIMP(n),
            0x8c => Opcode::NIMP(n),
            0x8d => Opcode::NIMP(n),
            0x8e => Opcode::NIMP(n),
            0x8f => Opcode::NIMP(n),
            //
            0x90 => Opcode::NIMP(n),
            0x91 => Opcode::NIMP(n),
            0x92 => Opcode::NIMP(n),
            0x93 => Opcode::NIMP(n),
            0x94 => Opcode::NIMP(n),
            0x95 => Opcode::NIMP(n),
            0x96 => Opcode::NIMP(n),
            0x97 => Opcode::NIMP(n),
            0x98 => Opcode::NIMP(n),
            0x99 => Opcode::NIMP(n),
            0x9a => Opcode::NIMP(n),
            0x9b => Opcode::NIMP(n),
            0x9c => Opcode::NIMP(n),
            0x9d => Opcode::NIMP(n),
            0x9e => Opcode::NIMP(n),
            0x9f => Opcode::NIMP(n),
            //
            0xa0 => Opcode::NIMP(n),
            0xa1 => Opcode::NIMP(n),
            0xa2 => Opcode::NIMP(n),
            0xa3 => Opcode::NIMP(n),
            0xa4 => Opcode::NIMP(n),
            0xa5 => Opcode::NIMP(n),
            0xa6 => Opcode::NIMP(n),
            0xa7 => Opcode::NIMP(n),
            0xa8 => Opcode::NIMP(n),
            0xa9 => Opcode::NIMP(n),
            0xaa => Opcode::NIMP(n),
            0xab => Opcode::NIMP(n),
            0xac => Opcode::NIMP(n),
            0xad => Opcode::NIMP(n),
            0xae => Opcode::NIMP(n),
            0xaf => Opcode::NIMP(n),
            //
            0xb0 => Opcode::NIMP(n),
            0xb1 => Opcode::NIMP(n),
            0xb2 => Opcode::NIMP(n),
            0xb3 => Opcode::NIMP(n),
            0xb4 => Opcode::NIMP(n),
            0xb5 => Opcode::NIMP(n),
            0xb6 => Opcode::NIMP(n),
            0xb7 => Opcode::NIMP(n),
            0xb8 => Opcode::NIMP(n),
            0xb9 => Opcode::NIMP(n),
            0xba => Opcode::NIMP(n),
            0xbb => Opcode::NIMP(n),
            0xbc => Opcode::NIMP(n),
            0xbd => Opcode::NIMP(n),
            0xbe => Opcode::NIMP(n),
            0xbf => Opcode::NIMP(n),
            //
            0xc0 => Opcode::NIMP(n),
            0xc1 => Opcode::NIMP(n),
            0xc2 => Opcode::NIMP(n),
            0xc3 => Opcode::NIMP(n),
            0xc4 => Opcode::NIMP(n),
            0xc5 => Opcode::NIMP(n),
            0xc6 => Opcode::NIMP(n),
            0xc7 => Opcode::NIMP(n),
            0xc8 => Opcode::NIMP(n),
            0xc9 => Opcode::NIMP(n),
            0xca => Opcode::NIMP(n),
            0xcb => Opcode::NIMP(n),
            0xcc => Opcode::NIMP(n),
            0xcd => Opcode::NIMP(n),
            0xce => Opcode::NIMP(n),
            0xcf => Opcode::NIMP(n),
            //
            0xd0 => Opcode::NIMP(n),
            0xd1 => Opcode::NIMP(n),
            0xd2 => Opcode::NIMP(n),
            0xd3 => Opcode::NIMP(n),
            0xd4 => Opcode::NIMP(n),
            0xd5 => Opcode::NIMP(n),
            0xd6 => Opcode::NIMP(n),
            0xd7 => Opcode::NIMP(n),
            0xd8 => Opcode::NIMP(n),
            0xd9 => Opcode::NIMP(n),
            0xda => Opcode::NIMP(n),
            0xdb => Opcode::NIMP(n),
            0xdc => Opcode::NIMP(n),
            0xdd => Opcode::NIMP(n),
            0xde => Opcode::NIMP(n),
            0xdf => Opcode::NIMP(n),
            //
            0xe0 => Opcode::NIMP(n),
            0xe1 => Opcode::NIMP(n),
            0xe2 => Opcode::NIMP(n),
            0xe3 => Opcode::NIMP(n),
            0xe4 => Opcode::NIMP(n),
            0xe5 => Opcode::NIMP(n),
            0xe6 => Opcode::NIMP(n),
            0xe7 => Opcode::NIMP(n),
            0xe8 => Opcode::NIMP(n),
            0xe9 => Opcode::NIMP(n),
            0xea => Opcode::NIMP(n),
            0xeb => Opcode::NIMP(n),
            0xec => Opcode::NIMP(n),
            0xed => Opcode::NIMP(n),
            0xee => Opcode::NIMP(n),
            0xef => Opcode::NIMP(n),
            //
            0xf0 => Opcode::NIMP(n),
            0xf1 => Opcode::NIMP(n),
            0xf2 => Opcode::NIMP(n),
            0xf3 => Opcode::NIMP(n),
            0xf4 => Opcode::NIMP(n),
            0xf5 => Opcode::NIMP(n),
            0xf6 => Opcode::NIMP(n),
            0xf7 => Opcode::NIMP(n),
            0xf8 => Opcode::NIMP(n),
            0xf9 => Opcode::NIMP(n),
            0xfa => Opcode::NIMP(n),
            0xfb => Opcode::NIMP(n),
            0xfc => Opcode::NIMP(n),
            0xfd => Opcode::NIMP(n),
            0xfe => Opcode::NIMP(n),
            0xff => Opcode::NIMP(n),
        }
    }
}